stages:
  data_ingestion:
    cmd: python -m src.textSummarizer.pipeline.stage_01_data_ingestion
    deps:
      - src/textSummarizer/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/samsum_dataset


  data_transformation:
    cmd: python -m src.textSummarizer.pipeline.stage_02_data_transformation
    deps:
      - src/textSummarizer/pipeline/stage_02_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/samsum_dataset/train/data-00000-of-00001.arrow
      - artifacts/data_ingestion/samsum_dataset/train/dataset_info.json
    outs:
      - artifacts/data_transformation/samsum_dataset


  model_training:
    cmd: python -m src.textSummarizer.pipeline.stage_03_model_trainer
    deps:
      - src/textSummarizer/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_transformation/samsum_dataset
    params:
      - TrainingArguments.num_train_epochs
      - TrainingArguments.warmup_steps
      - TrainingArguments.per_device_train_batch_size
      - TrainingArguments.weight_decay
      - TrainingArguments.logging_steps
      - TrainingArguments.evaluation_strategy
      - TrainingArguments.eval_steps
      - TrainingArguments.save_steps
      - TrainingArguments.gradient_accumulation_steps
    outs:
      - artifacts/model_trainer/distilbart-samsum-model


  evaluation:
    cmd: python -m src.textSummarizer.pipeline.stage_04_model_evaluation
    deps:
      - src/textSummarizer/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_transformation/samsum_dataset
      - artifacts/model_trainer/distilbart-samsum-model
      - artifacts/model_trainer/tokenizer
    metrics:
    - artifacts/model_evaluation/metrics.csv:
        cache: false
